[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#286b58"
backgroundColor = "#f3f5f0"
secondaryBackgroundColor = "#e7eee8"
textColor = "#202b28"
font = "sans serif"